name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_URL: 'http://localhost:3333/v1'
      SOCKET_URL: 'http://localhost:3333'
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          cache: 'yarn'
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          yarn
          yarn test
      - uses: codecov/codecov-action@v1
        with:
          directory: ./tests/coverage/
